//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertRuleDataPoint
    {
        public int Id { get; set; }
        public int AlertRuleSetupId { get; set; }
        public string ObjectId { get; set; }
        public Nullable<int> ObjectFkId { get; set; }
        public string DataFieldId { get; set; }
        public Nullable<int> DataFieldFkId { get; set; }
        public Nullable<int> ObjectNo { get; set; }
        public Nullable<System.DateTime> FirstOccurance { get; set; }
        public Nullable<System.DateTime> LastOccurance { get; set; }
        public Nullable<int> OccuranceCount { get; set; }
        public Nullable<double> SameDataOccuranceValue { get; set; }
    }
}
