//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacnetObjectDatafieldMapping
    {
        public int Id { get; set; }
        public Nullable<int> ObjectFkId { get; set; }
        public string ObjectId { get; set; }
        public Nullable<int> DatafieldFkId { get; set; }
        public string DatafieldId { get; set; }
        public string BacnetOjectId { get; set; }
        public string BacnetDatafiledId { get; set; }
    }
}
