//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMSReportFileProgress
    {
        public long Id { get; set; }
        public Nullable<int> UserFkId { get; set; }
        public Nullable<int> BuildingFkId { get; set; }
        public string DisplayName { get; set; }
        public string ExcelFileName { get; set; }
        public string ProcessedJSONFileName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
