//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingDataPoint
    {
        public int Id { get; set; }
        public int BuildingFkId { get; set; }
        public int ObjectFkId { get; set; }
        public int DataFieldFkId { get; set; }
        public string BuildingId { get; set; }
        public string ObjectId { get; set; }
        public string DataFieldId { get; set; }
        public int ObjectNo { get; set; }
        public string ObjectDisplayName { get; set; }
        public string DataFieldDisplayName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsComputed { get; set; }
        public Nullable<System.DateTime> LastDataReceived { get; set; }
    }
}
