//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingObjectMapping
    {
        public int Id { get; set; }
        public string BuildingId { get; set; }
        public string ObjectId { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> CHWPTemperatureObjectNo { get; set; }
        public Nullable<int> CWPTemperatureObjectNo { get; set; }
        public Nullable<int> CHWPPowerObjectNo { get; set; }
        public Nullable<int> CHPowerObjectNo { get; set; }
        public Nullable<int> CWPPowerObjectNo { get; set; }
        public Nullable<int> CTPowerObjectNo { get; set; }
        public Nullable<int> CHWPFlowrateObjectNo { get; set; }
        public Nullable<int> CWPFlowrateObjectNo { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Url { get; set; }
    }
}
