//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputedInfo
    {
        public int AutoId { get; set; }
        public int BuildingFkId { get; set; }
        public string BuildingId { get; set; }
        public string ObjectName { get; set; }
        public string Module { get; set; }
        public string ValueType { get; set; }
        public string Value { get; set; }
    }
}
