//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designed
    {
        public int Id { get; set; }
        public int BuildingFkId { get; set; }
        public string BuildingId { get; set; }
        public int ObjectFkId { get; set; }
        public string ObjectId { get; set; }
        public int DataFieldFkId { get; set; }
        public string DataFieldId { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string IPAddress { get; set; }
    }
}
