//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricityMeterReading
    {
        public string BuildingId { get; set; }
        public int BuildingFkId { get; set; }
        public int BuildingUnitFkId { get; set; }
        public int MeterFkId { get; set; }
        public int TenantFkId { get; set; }
        public Nullable<double> Value { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
