//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricityBillParameter
    {
        public int Id { get; set; }
        public Nullable<int> BuildingFkId { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string MaxDecimalPoints { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string BillType { get; set; }
        public string ReturnFormat { get; set; }
        public Nullable<bool> IsExistInExpression { get; set; }
        public string Expression { get; set; }
        public Nullable<bool> IsComputed { get; set; }
    }
}
