//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyBill
    {
        public int Id { get; set; }
        public string BuildingId { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<double> Value { get; set; }
    }
}
