//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelToReportDataPoint
    {
        public int Id { get; set; }
        public string BuildingId { get; set; }
        public Nullable<int> BuildingFkId { get; set; }
        public string DisplayName { get; set; }
        public string ObjectId { get; set; }
        public Nullable<int> ObjectFkId { get; set; }
        public string DataFieldId { get; set; }
        public Nullable<int> DataFieldFkId { get; set; }
        public Nullable<int> ObjectNo { get; set; }
        public Nullable<bool> IsComputed { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
