//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportMapping
    {
        public int Id { get; set; }
        public Nullable<int> BuildingFkId { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> DatapointId { get; set; }
        public string ObjectId { get; set; }
        public string DataFieldId { get; set; }
        public Nullable<int> ObjectNo { get; set; }
        public Nullable<int> DeviceFkId { get; set; }
        public string TableName { get; set; }
        public string SensorName { get; set; }
    }
}
