//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlagAlertTrack
    {
        public int Id { get; set; }
        public string BuildingId { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> TillNowDateTime { get; set; }
        public Nullable<int> TillNowHeatBalanceTotalCount { get; set; }
        public Nullable<int> TillNowHeatBalanceInRangeCount { get; set; }
        public Nullable<double> TillNowHeatBalanceInRangePercentage { get; set; }
        public Nullable<double> TillNowHighestBaseline { get; set; }
        public Nullable<int> TillNowEfficiencyTotalCount { get; set; }
        public Nullable<double> TillNowEfficiencySum { get; set; }
        public Nullable<double> TillNowSystemEfficiencyAverage { get; set; }
    }
}
