//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthyRangeSetup
    {
        public int Id { get; set; }
        public string BuildingId { get; set; }
        public int DeviceFkId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public double interval { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<double> yAxisMin { get; set; }
        public Nullable<double> yAxisMax { get; set; }
    }
}
