//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuToTab
    {
        public int Id { get; set; }
        public Nullable<int> MenuFkId { get; set; }
        public Nullable<int> TabFkId { get; set; }
        public Nullable<int> BuildingFkId { get; set; }
    }
}
