//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sbn_cwDBEntities : DbContext
    {
        public sbn_cwDBEntities()
            : base("name=sbn_cwDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alert> Alerts { get; set; }
        public DbSet<AlertData> AlertDatas { get; set; }
        public DbSet<AlertMaster> AlertMasters { get; set; }
        public DbSet<AlertProccessingTrack> AlertProccessingTracks { get; set; }
        public DbSet<AlertRuleDataPoint> AlertRuleDataPoints { get; set; }
        public DbSet<AlertRuleSetup> AlertRuleSetups { get; set; }
        public DbSet<AlertRuleType> AlertRuleTypes { get; set; }
        public DbSet<AlertSuppress> AlertSuppresses { get; set; }
        public DbSet<BacnetObjectDatafieldMapping> BacnetObjectDatafieldMappings { get; set; }
        public DbSet<Baseline> Baselines { get; set; }
        public DbSet<BaselineCommon> BaselineCommons { get; set; }
        public DbSet<BaselineCommonDataPoint> BaselineCommonDataPoints { get; set; }
        public DbSet<BaselineLearnedDate> BaselineLearnedDates { get; set; }
        public DbSet<BaselineMaster> BaselineMasters { get; set; }
        public DbSet<BillFile> BillFiles { get; set; }
        public DbSet<BillMapping> BillMappings { get; set; }
        public DbSet<BillParameter> BillParameters { get; set; }
        public DbSet<BMSReportFileProgress> BMSReportFileProgresses { get; set; }
        public DbSet<Building> Buildings { get; set; }
        public DbSet<BuildingDataPoint> BuildingDataPoints { get; set; }
        public DbSet<BuildingGFA> BuildingGFAs { get; set; }
        public DbSet<BuildingHeadersMapping> BuildingHeadersMappings { get; set; }
        public DbSet<BuildingObject> BuildingObjects { get; set; }
        public DbSet<BuildingObjectData> BuildingObjectDatas { get; set; }
        public DbSet<BuildingObjectMapping> BuildingObjectMappings { get; set; }
        public DbSet<BuildingStaticInformation> BuildingStaticInformations { get; set; }
        public DbSet<BuildingType> BuildingTypes { get; set; }
        public DbSet<BuildingUser> BuildingUsers { get; set; }
        public DbSet<BuildingValueLimit> BuildingValueLimits { get; set; }
        public DbSet<Computation> Computations { get; set; }
        public DbSet<ComputedInfo> ComputedInfoes { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<CWAlert> CWAlerts { get; set; }
        public DbSet<CWAlertRuleSetup> CWAlertRuleSetups { get; set; }
        public DbSet<CWBaselineCommon> CWBaselineCommons { get; set; }
        public DbSet<CWBuildingDataPoint> CWBuildingDataPoints { get; set; }
        public DbSet<CWElectricityBillParameter> CWElectricityBillParameters { get; set; }
        public DbSet<CWElectricityBillReading> CWElectricityBillReadings { get; set; }
        public DbSet<DataField> DataFields { get; set; }
        public DbSet<Designed> Designeds { get; set; }
        public DbSet<ElectricityBillParameter> ElectricityBillParameters { get; set; }
        public DbSet<ElectricityBillReading> ElectricityBillReadings { get; set; }
        public DbSet<ElectricityBillReadingV2> ElectricityBillReadingV2 { get; set; }
        public DbSet<ElectricityBuildingUnit> ElectricityBuildingUnits { get; set; }
        public DbSet<ElectricityMeter> ElectricityMeters { get; set; }
        public DbSet<ElectricityTenant> ElectricityTenants { get; set; }
        public DbSet<ElectricityTenantCategory> ElectricityTenantCategories { get; set; }
        public DbSet<EmailSummaryNotifyGroup> EmailSummaryNotifyGroups { get; set; }
        public DbSet<EmailSummaryNotifyUser> EmailSummaryNotifyUsers { get; set; }
        public DbSet<EnergyBill> EnergyBills { get; set; }
        public DbSet<ExcelToReportDataPoint> ExcelToReportDataPoints { get; set; }
        public DbSet<ExportMapping> ExportMappings { get; set; }
        public DbSet<Expression> Expressions { get; set; }
        public DbSet<FlagAlertTrack> FlagAlertTracks { get; set; }
        public DbSet<GasBillParameter> GasBillParameters { get; set; }
        public DbSet<GasBillReading> GasBillReadings { get; set; }
        public DbSet<GasBillReadingV2> GasBillReadingV2 { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<HealthyRangeSetup> HealthyRangeSetups { get; set; }
        public DbSet<MenuAuthentication> MenuAuthentications { get; set; }
        public DbSet<ModuleConfiguration> ModuleConfigurations { get; set; }
        public DbSet<NotifyUser> NotifyUsers { get; set; }
        public DbSet<NotifyUserGroup> NotifyUserGroups { get; set; }
        public DbSet<Object> Objects { get; set; }
        public DbSet<ObjectData> ObjectDatas { get; set; }
        public DbSet<PinMapping> PinMappings { get; set; }
        public DbSet<PinToDashboard> PinToDashboards { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Reading> Readings { get; set; }
        public DbSet<ReportTable> ReportTables { get; set; }
        public DbSet<RoleBuildingMapping> RoleBuildingMappings { get; set; }
        public DbSet<SchematicReading> SchematicReadings { get; set; }
        public DbSet<Scheme> Schemes { get; set; }
        public DbSet<SensorDevice> SensorDevices { get; set; }
        public DbSet<SensorSyncTable> SensorSyncTables { get; set; }
        public DbSet<TempRawData> TempRawDatas { get; set; }
        public DbSet<TempReading> TempReadings { get; set; }
        public DbSet<TempReading_Temp> TempReading_Temp { get; set; }
        public DbSet<Threshold> Thresholds { get; set; }
        public DbSet<UserBuildingBookmark> UserBuildingBookmarks { get; set; }
        public DbSet<UserBuildingMapping> UserBuildingMappings { get; set; }
        public DbSet<UserGroup> UserGroups { get; set; }
        public DbSet<UserSession> UserSessions { get; set; }
        public DbSet<WaterBillParameter> WaterBillParameters { get; set; }
        public DbSet<WaterBillReading> WaterBillReadings { get; set; }
        public DbSet<WaterBillReadingV2> WaterBillReadingV2 { get; set; }
        public DbSet<BuildingToModule> BuildingToModules { get; set; }
        public DbSet<ClientGroup> ClientGroups { get; set; }
        public DbSet<ClientGroupToBuilding> ClientGroupToBuildings { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<MenuToTab> MenuToTabs { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<ModuleToMenu> ModuleToMenus { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RolePermission> RolePermissions { get; set; }
        public DbSet<RoleToUserAction> RoleToUserActions { get; set; }
        public DbSet<Tab> Tabs { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserAction> UserActions { get; set; }
        public DbSet<UserLog> UserLogs { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<UserToBuilding> UserToBuildings { get; set; }
        public DbSet<UserToClientGroup> UserToClientGroups { get; set; }
        public DbSet<ElectricityMeterReading> ElectricityMeterReadings { get; set; }
        public DbSet<ElectricityUnitTenantMapping> ElectricityUnitTenantMappings { get; set; }
        public DbSet<IAQReading> IAQReadings { get; set; }
        public DbSet<missingDataTemp7> missingDataTemp7 { get; set; }
        public DbSet<ReadingTestV2> ReadingTestV2 { get; set; }
        public DbSet<ReadingV2> ReadingV2 { get; set; }
        public DbSet<ReadingV3> ReadingV3 { get; set; }
        public DbSet<ReportTablesExpression> ReportTablesExpressions { get; set; }
        public DbSet<TempReading_TempV2> TempReading_TempV2 { get; set; }
        public DbSet<TempReadingTestV2> TempReadingTestV2 { get; set; }
        public DbSet<TempReadingV2> TempReadingV2 { get; set; }
        public DbSet<TempReadingV3> TempReadingV3 { get; set; }
        public DbSet<TokenMapping> TokenMappings { get; set; }
    }
}
