//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyUserGroup
    {
        public int SL { get; set; }
        public Nullable<int> AlertRuleSetupId { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
