//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinMapping
    {
        public int Id { get; set; }
        public Nullable<int> UserFkId { get; set; }
        public Nullable<int> BuildingFkId { get; set; }
        public Nullable<int> ObjectFkId { get; set; }
        public Nullable<int> DataFieldFkId { get; set; }
        public Nullable<int> ObjectNo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Type { get; set; }
        public string WeekDays { get; set; }
        public string Unit { get; set; }
        public Nullable<int> DecimalPoint { get; set; }
        public string YaxisText { get; set; }
        public string ChartTitle { get; set; }
        public string IconClass { get; set; }
        public Nullable<double> HighCap { get; set; }
        public Nullable<double> LowCap { get; set; }
        public string XaxisText { get; set; }
        public string ChartType { get; set; }
        public string Baseline { get; set; }
        public string ObjectFkIdList { get; set; }
        public string DataFieldFkIdList { get; set; }
        public Nullable<int> DeviceFkId { get; set; }
        public string ReadingTypeName { get; set; }
        public string TableName { get; set; }
        public string Year { get; set; }
        public Nullable<int> SizeX { get; set; }
        public Nullable<int> SizeY { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<int> Row { get; set; }
        public string ChartUIId { get; set; }
    }
}
