//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinToDashboard
    {
        public int Id { get; set; }
        public int UserFkId { get; set; }
        public int BuildingFkId { get; set; }
        public string ChartType { get; set; }
        public string Baseline { get; set; }
        public Nullable<int> DeviceFkId { get; set; }
        public string ControllerName { get; set; }
        public string ReadingTypeName { get; set; }
        public string TableName { get; set; }
        public string Datapoint { get; set; }
        public string SeriesName { get; set; }
        public string ChartTitle { get; set; }
        public string IconClass { get; set; }
        public string xAxisText { get; set; }
        public string yAxisText { get; set; }
        public string xAxisUnit { get; set; }
        public string yAxisUnit { get; set; }
        public string xAxisDecimalPoints { get; set; }
        public string yAxisDecimalPoints { get; set; }
        public string HighCaps { get; set; }
        public string LowCaps { get; set; }
        public int SizeX { get; set; }
        public int SizeY { get; set; }
        public int Col { get; set; }
        public int Row { get; set; }
    }
}
