//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTablesExpression
    {
        public int BuildingFkId { get; set; }
        public string ParameterName { get; set; }
        public string TableName { get; set; }
        public string Unit { get; set; }
        public int OrderId { get; set; }
        public string Expr { get; set; }
    }
}
