//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorDevice
    {
        public int Id { get; set; }
        public string BuildingId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string DeviceId { get; set; }
        public string MacAddress { get; set; }
        public string SerialNumber { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsComputed { get; set; }
        public Nullable<bool> IsSmart { get; set; }
        public string Icon { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Color { get; set; }
    }
}
