//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempReadingV3
    {
        public int BuildingFkId { get; set; }
        public int ObjectFkId { get; set; }
        public int DataFieldFkId { get; set; }
        public double Value { get; set; }
        public short ObjectNo { get; set; }
        public string ExpressionColumn { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string BuildingId { get; set; }
        public string ObjectId { get; set; }
        public string DataFieldId { get; set; }
    }
}
