//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempRawData
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<double> ChilledWaterHeaderSupplyFlow { get; set; }
        public Nullable<double> ChilledWaterHeaderReturnTemperature { get; set; }
        public Nullable<double> ChilledWaterHeaderSupplyTemperature { get; set; }
        public Nullable<double> CondenserHeaderSupplyFlow { get; set; }
        public Nullable<double> CondenserHeaderReturnTemperature { get; set; }
        public Nullable<double> CondenserHeaderSupplyTemperature { get; set; }
        public Nullable<double> ChillerPower1 { get; set; }
        public Nullable<double> ChillerPower2 { get; set; }
        public Nullable<double> ChillerPower3 { get; set; }
        public Nullable<double> ChillerPower4 { get; set; }
        public Nullable<double> ChillerPower5 { get; set; }
        public Nullable<double> CondenserPumpPower1 { get; set; }
        public Nullable<double> CondenserPumpPower2 { get; set; }
        public Nullable<double> CondenserPumpPower3 { get; set; }
        public Nullable<double> CondenserPumpPower4 { get; set; }
        public Nullable<double> CondenserPumpPower5 { get; set; }
        public Nullable<double> CoolingTowerPower1 { get; set; }
        public Nullable<double> CoolingTowerPower2 { get; set; }
        public Nullable<double> CoolingTowerPower3 { get; set; }
        public Nullable<double> CoolingTowerPower4 { get; set; }
        public Nullable<double> ChillerWaterPumpPower1 { get; set; }
        public Nullable<double> ChillerWaterPumpPower2 { get; set; }
        public Nullable<double> ChillerWaterPumpPower3 { get; set; }
        public Nullable<double> ChillerWaterPumpPower4 { get; set; }
        public Nullable<double> ChillerWaterPumpPower5 { get; set; }
    }
}
