//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedular_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int Id { get; set; }
        public Nullable<int> RolePermissionFkId { get; set; }
        public Nullable<int> UserFkId { get; set; }
        public Nullable<int> NavigationFkId { get; set; }
        public Nullable<int> TabFkId { get; set; }
        public string TypeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BuildingFkId { get; set; }
    }
}
